/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package basic75;

import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import static java.lang.Thread.sleep;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

/**
 *
 * @author HP
 */
public class LoginFrame extends javax.swing.JFrame {

    /**
     * Creates new form LoginFrame
     */
    public PreparedStatement pst=null;
    public ResultSet rs=null;
    
    public LoginFrame() {
        initComponents();
        
        this.setLocationRelativeTo(null);
        this.setExtendedState(this.getExtendedState() | this.MAXIMIZED_BOTH);
        this.getRootPane().setDefaultButton(loginB);
        
        //imageL.setIcon(Basic75.ResizeImage(new javax.swing.ImageIcon(getClass().getResource("/images/gates3.jpg")), imageL));

        errorL.setText("");
        showC.addItemListener(new ItemListener()
        {
            public void itemStateChanged(ItemEvent ie)
                {
                    if(showC.isSelected())
                        passwordF.setEchoChar((char)0);
                    else
                        passwordF.setEchoChar('*');
                }
        
    });
        welcomeP.setVisible(true);
        loginP.setVisible(false);
        SplashThread st=new SplashThread ();
        st.start();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        loginP = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        loginIDF = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        passwordF = new javax.swing.JPasswordField();
        showC = new javax.swing.JCheckBox();
        loginB = new javax.swing.JButton();
        RegisterL = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        welcomeP = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        DataBaseP = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        dbLoginIDT = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        dbPasswordT = new javax.swing.JPasswordField();
        submitDbB = new javax.swing.JButton();
        backL = new javax.swing.JLabel();
        errorL = new javax.swing.JLabel();
        imageL = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setLayout(null);

        jPanel4.setOpaque(false);
        jPanel4.setLayout(new java.awt.CardLayout());

        loginP.setOpaque(false);

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 22)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Login Id");

        loginIDF.setText("l");
        loginIDF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginIDFActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 1, 22)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Password");

        passwordF.setText("l");
        passwordF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordFActionPerformed(evt);
            }
        });

        showC.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        showC.setForeground(new java.awt.Color(255, 255, 255));
        showC.setText("show");
        showC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showCActionPerformed(evt);
            }
        });

        loginB.setText("Log In");
        loginB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginBActionPerformed(evt);
            }
        });

        RegisterL.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        RegisterL.setForeground(new java.awt.Color(255, 255, 255));
        RegisterL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        RegisterL.setText("<html><u>New User? Register here first. </u></html>");
        RegisterL.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        RegisterL.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        RegisterL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RegisterLMouseClicked(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Comic Sans MS", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("LogIn To 75");

        jLabel8.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Database Settings");
        jLabel8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout loginPLayout = new javax.swing.GroupLayout(loginP);
        loginP.setLayout(loginPLayout);
        loginPLayout.setHorizontalGroup(
            loginPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginPLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(loginPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginPLayout.createSequentialGroup()
                        .addGroup(loginPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(RegisterL, javax.swing.GroupLayout.PREFERRED_SIZE, 409, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(loginPLayout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(loginIDF, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(loginPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(loginB, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, loginPLayout.createSequentialGroup()
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(passwordF, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(3, 3, 3)
                                    .addComponent(showC))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34))
        );
        loginPLayout.setVerticalGroup(
            loginPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginPLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(loginPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(loginIDF, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(loginPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(loginPLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(passwordF, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(showC, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(loginB, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(RegisterL, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel4.add(loginP, "card2");

        welcomeP.setOpaque(false);

        jLabel4.setFont(new java.awt.Font("Comic Sans MS", 1, 48)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("WELCOME TO ");

        jLabel5.setFont(new java.awt.Font("Comic Sans MS", 1, 72)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("75");

        javax.swing.GroupLayout welcomePLayout = new javax.swing.GroupLayout(welcomeP);
        welcomeP.setLayout(welcomePLayout);
        welcomePLayout.setHorizontalGroup(
            welcomePLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(welcomePLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(welcomePLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 466, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        welcomePLayout.setVerticalGroup(
            welcomePLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(welcomePLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(120, Short.MAX_VALUE))
        );

        jPanel4.add(welcomeP, "card3");

        DataBaseP.setOpaque(false);

        jLabel6.setFont(new java.awt.Font("Comic Sans MS", 1, 22)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Computer Name");

        dbLoginIDT.setText("sytem");
        dbLoginIDT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dbLoginIDTActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Comic Sans MS", 1, 22)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Password");

        dbPasswordT.setText("5697kishan");
        dbPasswordT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dbPasswordTActionPerformed(evt);
            }
        });

        submitDbB.setText("Submit");
        submitDbB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitDbBActionPerformed(evt);
            }
        });

        backL.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        backL.setForeground(new java.awt.Color(255, 255, 255));
        backL.setText("back");
        backL.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        backL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backLMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout DataBasePLayout = new javax.swing.GroupLayout(DataBaseP);
        DataBaseP.setLayout(DataBasePLayout);
        DataBasePLayout.setHorizontalGroup(
            DataBasePLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DataBasePLayout.createSequentialGroup()
                .addGroup(DataBasePLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DataBasePLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(backL, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(DataBasePLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(DataBasePLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 92, Short.MAX_VALUE)
                        .addGroup(DataBasePLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dbLoginIDT, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dbPasswordT, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
            .addGroup(DataBasePLayout.createSequentialGroup()
                .addGap(133, 133, 133)
                .addComponent(submitDbB, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        DataBasePLayout.setVerticalGroup(
            DataBasePLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DataBasePLayout.createSequentialGroup()
                .addComponent(backL, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70)
                .addGroup(DataBasePLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DataBasePLayout.createSequentialGroup()
                        .addComponent(dbLoginIDT, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(dbPasswordT, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(DataBasePLayout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(40, 40, 40)
                .addComponent(submitDbB, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(90, Short.MAX_VALUE))
        );

        jPanel4.add(DataBaseP, "card4");

        jPanel2.add(jPanel4);
        jPanel4.setBounds(250, 250, 490, 360);

        errorL.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        errorL.setForeground(new java.awt.Color(255, 0, 51));
        jPanel2.add(errorL);
        errorL.setBounds(290, 180, 413, 67);

        imageL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imageL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ezgif.com-resize.gif"))); // NOI18N
        jPanel2.add(imageL);
        imageL.setBounds(80, 40, 810, 750);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 919, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 820, Short.MAX_VALUE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginBActionPerformed
        errorL.setText("");
        if(loginIDF.getText().length()==0||loginIDF.getText().trim().length()==0||String.valueOf(passwordF.getPassword()).length()==0||String.valueOf(passwordF.getPassword()).trim().length()==0)
        {
          
          errorL.setText("Error: Incomplete info!!! Please Fill Complete Info and Try Again");
        }
        else
        {
            Connection con=null;
            int found=-1;
            con=Connect.connect();
            try
            {
                pst=con.prepareStatement("select * from usert where loginid =? and password=?", ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_UPDATABLE);
                pst.setString(1, loginIDF.getText());
                pst.setString(2, String.valueOf(passwordF.getPassword()));
                rs= pst.executeQuery();
                rs.last();
                found =rs.getRow();
                if(found!=1)
                {
                    errorL.setText("Error: Incorrect loginID or Password!!! TRY AGAIN");
                }
            }
            catch(SQLException se)
            {
                errorL.setText("Error: LoginFrame.loginB: "+se.getMessage());
            }
            finally
            {
               if(con!=null)
               {
                    try
                    {
                        
                        if(found==1)
                        {
                         errorL.setText("Succecsfully logged in");
                         Basic75.firstName=rs.getString(2);
                         Basic75.lastName=rs.getString(3);
                         Basic75.loginID=rs.getString(4);
                         //Basic75.password=rs.getString(5);
                         // Basic75.currentSem=rs.getInt(6);
                         Basic75.setCurrentSem(con);
                         
                         SplashScreenFrame sf=new SplashScreenFrame();
                         sf.setVisible(true);
                         this.setVisible(false);
                        
                        }
                        con.close();
                    }
                    catch(SQLException se)
                    {
                        errorL.setText("Error: Error closing connection: "+se.getMessage());
                    }
               }
                
            }
        }
        
    }//GEN-LAST:event_loginBActionPerformed

    private void RegisterLMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegisterLMouseClicked
     RegisterFrame rf=new RegisterFrame();
     rf.setVisible(true);
     this.setVisible(false);
    }//GEN-LAST:event_RegisterLMouseClicked

    private void showCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showCActionPerformed
        
    }//GEN-LAST:event_showCActionPerformed

    private void loginIDFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginIDFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_loginIDFActionPerformed

    private void passwordFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordFActionPerformed

    private void dbLoginIDTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dbLoginIDTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dbLoginIDTActionPerformed

    private void dbPasswordTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dbPasswordTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dbPasswordTActionPerformed

    private void submitDbBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitDbBActionPerformed
        Basic75.DbLoginID=dbLoginIDT.getText();
        Basic75.DbPassword=String.valueOf(dbPasswordT.getPassword());
        //System.out.println("Basic75.DbPassword: "+Basic75.DbPassword);
    }//GEN-LAST:event_submitDbBActionPerformed

    private void backLMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backLMouseClicked
        loginP.setVisible(true);
        DataBaseP.setVisible(false);
    }//GEN-LAST:event_backLMouseClicked

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        loginP.setVisible(false);
        DataBaseP.setVisible(true);
    }//GEN-LAST:event_jLabel8MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginFrame().setVisible(true);
            }
        });
    }
class SplashThread extends Thread
    {
        public void run()
        {
        try
        {
            sleep(3000);
        }
        catch(InterruptedException ie)
        {
            System.out.println("Error: Interrupted, LoginFrame "+ie.getMessage());
            errorL.setText("Main Thread Interrupted");
        }
        loginP.setVisible(true);
        welcomeP.setVisible(false);
            
            //dispose();
        }
        }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel DataBaseP;
    private javax.swing.JLabel RegisterL;
    private javax.swing.JLabel backL;
    private javax.swing.JTextField dbLoginIDT;
    private javax.swing.JPasswordField dbPasswordT;
    private javax.swing.JLabel errorL;
    private javax.swing.JLabel imageL;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JButton loginB;
    private javax.swing.JTextField loginIDF;
    private javax.swing.JPanel loginP;
    private javax.swing.JPasswordField passwordF;
    private javax.swing.JCheckBox showC;
    private javax.swing.JButton submitDbB;
    private javax.swing.JPanel welcomeP;
    // End of variables declaration//GEN-END:variables
}
