/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package basic75;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author HP
 */
public class SelectViewFrame extends javax.swing.JFrame {

    /**
     * Creates new form SelectViewFrame
     */
    DefaultTableModel dtm;
    int noOfSub[];
    int noOfLec[];
    int sem[];
    int workingDays[];
    public static String offSaturdays[];
    
    public SelectViewFrame() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setExtendedState(this.getExtendedState() | this.MAXIMIZED_BOTH);

        dtm = (DefaultTableModel)semT.getModel();
        setSelectView();
    }
    
    public void setSelectView()
    {
        Connection con=Connect.connect();
        try
        {
            PreparedStatement pst=con.prepareStatement("select * from "+Basic75.loginID+"BASIC order by STARTDATE DESC",ResultSet.TYPE_SCROLL_INSENSITIVE,ResultSet.CONCUR_READ_ONLY);
            ResultSet rs = pst.executeQuery();
            rs.last();
            
            int row = rs.getRow();
            noOfSub=new int[row+1];
            noOfLec=new int[row+1];
            sem=new int[row+1];
            workingDays=new int[row+1];
            SelectViewFrame.offSaturdays=new String[row+1];
            
            //System.out.println("row "+row);
            rs.beforeFirst();
            dtm.setRowCount(row+1);
            int i=0;
            while(rs.next())
            {
                //System.out.println(rs.getInt(1)+""+rs.getDate(2)+rs.getDate(3));
                semT.setValueAt("semester "+rs.getInt(9), i, 0);
                semT.setValueAt(rs.getDate(1), i, 1);
                semT.setValueAt(rs.getDate(2), i, 2);
                sem[i]=rs.getInt(9);
                workingDays[i]=rs.getInt(3);
                noOfLec[i]=rs.getInt(4);
                noOfSub[i]=rs.getInt(5);
                offSaturdays[i]=rs.getString(6);
                
                if(i==0){
                    i=2;
                }
                else{
                    ++i;
                }
                
            }
            
        }
        catch(SQLException se)
        {
            System.out.println("Error: Selectview.setSelectView() "+se.getMessage());
            se.printStackTrace();
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        semT = new javax.swing.JTable();
        messageL = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        backL = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jPanel2.setOpaque(false);
        jPanel2.setLayout(null);

        jPanel3.setOpaque(false);

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Click on semester to view details ");

        semT.setBackground(new java.awt.Color(0, 0, 0));
        semT.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        semT.setFont(new java.awt.Font("Comic Sans MS", 1, 20)); // NOI18N
        semT.setForeground(new java.awt.Color(255, 255, 255));
        semT.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Semester", "Starting Date", "Last Date"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        semT.setFillsViewportHeight(true);
        semT.setGridColor(new java.awt.Color(0, 0, 0));
        semT.setRowHeight(40);
        semT.setSelectionBackground(new java.awt.Color(204, 204, 204));
        semT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                semTMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(semT);

        messageL.setFont(new java.awt.Font("Comic Sans MS", 1, 20)); // NOI18N
        messageL.setForeground(new java.awt.Color(255, 51, 51));
        messageL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(messageL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 828, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(messageL, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(290, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel3);
        jPanel3.setBounds(0, 10, 860, 750);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/753.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(20, 480, 830, 250);

        backL.setFont(new java.awt.Font("Comic Sans MS", 1, 20)); // NOI18N
        backL.setForeground(new java.awt.Color(255, 255, 255));
        backL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        backL.setText("back");
        backL.setToolTipText("go back to Home ");
        backL.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        backL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backLMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 860, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(backL, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(backL, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 767, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void semTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_semTMouseClicked
        if(semT.getSelectedRow()!=1){
            
            //System.out.println("Semester--->"+sem[semT.getSelectedRow()]);
            if(noOfSub[semT.getSelectedRow()]>0 && noOfLec[semT.getSelectedRow()]>0)
            {
                int r=semT.getSelectedRow();
               /* System.out.println(semT.getValueAt(r, 1));
                System.out.println(semT.getValueAt(r, 2));
                System.out.println(sem[r]);
                System.out.println(noOfSub[r]);
                System.out.println(noOfLec[r]);
                System.out.println(workingDays[r]);
                System.out.println(SelectViewFrame.offSaturdays[r]);*/
                viewFrame vf = new viewFrame((java.util.Date)semT.getValueAt(r, 1),(java.util.Date)semT.getValueAt(r, 2),sem[r],noOfSub[r],noOfLec[r],workingDays[r],SelectViewFrame.offSaturdays[r]);
                vf.setVisible(true);
                this.dispose();
            }
            else
            {
                messageL.setText("Sorry! Incomplete record for given semester. Click on some other semester to view records");
            }
            
        }
    }//GEN-LAST:event_semTMouseClicked

    private void backLMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backLMouseClicked
       Basic75.hf.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backLMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SelectViewFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SelectViewFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SelectViewFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SelectViewFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SelectViewFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backL;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel messageL;
    private javax.swing.JTable semT;
    // End of variables declaration//GEN-END:variables
}
