/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package basic75;

import static java.lang.String.valueOf;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JComboBox;
import javax.swing.JTextField;
import static oracle.net.aso.C11.i;

/**
 *
 * @author HP
 */
public class SettingsFrame extends javax.swing.JFrame {

    JComboBox targetC[]=null;
    JComboBox priorityC[]=null;
    boolean done=false;
    
    public SettingsFrame() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setExtendedState(this.getExtendedState() | this.MAXIMIZED_BOTH);
        firstHalfC.removeAllItems();
        firstHalfC.addItem("high");
        firstHalfC.addItem("average");
        firstHalfC.addItem("low");
        secondHalfC.removeAllItems();
        secondHalfC.addItem("high");
        secondHalfC.addItem("average");
        secondHalfC.addItem("low");
        
        firstHalfC.setSelectedItem(Basic75.firstHalfP);
        secondHalfC.setSelectedItem(Basic75.secondHalfP);
        done=true;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        targetP = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        firstHalfC = new javax.swing.JComboBox<>();
        secondHalfC = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        doneB = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        back1L = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        messsageL = new javax.swing.JLabel();
        back2L = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        submitB = new javax.swing.JButton();

		SubPriority sp= new SubPriority();
jScrollPane1 =sp.getPane();
targetC=sp.getTarget();
priorityC=sp.getPriority();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);
        jTabbedPane1.setFont(new java.awt.Font("Comic Sans MS", 1, 22)); // NOI18N

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));

        targetP.setBackground(new java.awt.Color(204, 204, 204));
        targetP.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED, null, new java.awt.Color(204, 204, 204), null, new java.awt.Color(255, 255, 255)));
        targetP.setOpaque(false);

        jLabel3.setFont(new java.awt.Font("Comic Sans MS", 1, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("First Half");

        firstHalfC.setFont(new java.awt.Font("Comic Sans MS", 0, 20)); // NOI18N
        firstHalfC.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        firstHalfC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstHalfCActionPerformed(evt);
            }
        });

        secondHalfC.setFont(new java.awt.Font("Comic Sans MS", 0, 20)); // NOI18N
        secondHalfC.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        secondHalfC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                secondHalfCActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Comic Sans MS", 1, 20)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Second Half");

        doneB.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        doneB.setText("Done");
        doneB.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        doneB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doneBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout targetPLayout = new javax.swing.GroupLayout(targetP);
        targetP.setLayout(targetPLayout);
        targetPLayout.setHorizontalGroup(
            targetPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, targetPLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(doneB, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, targetPLayout.createSequentialGroup()
                .addContainerGap(162, Short.MAX_VALUE)
                .addGroup(targetPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(targetPLayout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(firstHalfC, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(targetPLayout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(secondHalfC, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(162, Short.MAX_VALUE))
        );
        targetPLayout.setVerticalGroup(
            targetPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(targetPLayout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addGroup(targetPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(firstHalfC, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(77, 77, 77)
                .addGroup(targetPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(secondHalfC, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                .addComponent(doneB, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
        );

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/753.png"))); // NOI18N
        jLabel5.setText("jLabel5");

        back1L.setFont(new java.awt.Font("Comic Sans MS", 1, 20)); // NOI18N
        back1L.setForeground(new java.awt.Color(255, 255, 255));
        back1L.setText("back");
        back1L.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        back1L.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                back1LMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(0, 247, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(back1L, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(targetP, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(188, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(back1L, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(targetP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Session Priority", jPanel3);

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));

        back2L.setFont(new java.awt.Font("Comic Sans MS", 1, 20)); // NOI18N
        back2L.setForeground(new java.awt.Color(255, 255, 255));
        back2L.setText("back");
        back2L.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        back2L.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                back2LMouseClicked(evt);
            }
        });

        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel1.setOpaque(false);

        jScrollPane1.setBackground(new java.awt.Color(0, 0, 0));

        submitB.setText("Submit");
        submitB.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        submitB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(96, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 705, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(93, 93, 93))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(364, 364, 364)
                .addComponent(submitB, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 458, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addComponent(submitB, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(91, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(messsageL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(back2L, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(100, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(messsageL, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(back2L, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Edit Subject Priority & Target", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 754, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void submitBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitBActionPerformed
        
      Connection con=Connect.connect();
       try
       {
           PreparedStatement ps=con.prepareStatement("select priority,target from "+Basic75.loginID+"subjects"+Basic75.currentSem,ResultSet.TYPE_SCROLL_SENSITIVE,ResultSet.CONCUR_UPDATABLE);
           ResultSet rs=ps.executeQuery();
           int i=0;
           while(rs.next())
           {
               rs.updateString(1,valueOf(priorityC[i].getSelectedItem()));
               String s=(String)targetC[i].getSelectedItem();
               s=s.replace('%', ' ');
               s=s.trim();
               rs.updateInt(2,Integer.parseInt(s));
               rs.updateRow();
               i++;
           }
           Basic75.setSubjects(null, Basic75.subjects ,Basic75.priority, Basic75.target,Basic75.noOfSub,Basic75.currentSem);
       }
       catch(SQLException se)
       {
           System.out.println("Error in SettingsFrame.SubmitB(Target)"+se.getMessage());
       }
        finally
       {
           if(con!=null)
           {
               try
               {
                   con.close();
               }
               catch(SQLException se)
               {
                   System.out.println("Error in closing connection in SettingsFrame.SubmitB(Target)"+se.getMessage());
               }
           }
       }
        
    }//GEN-LAST:event_submitBActionPerformed

    private void firstHalfCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstHalfCActionPerformed
        if(done)
        {
            if(firstHalfC.getSelectedItem().equals("high"))
            {
                done=false;
                secondHalfC.removeAllItems();
                secondHalfC.addItem("low");
                done=true;
                
            }
            else if(firstHalfC.getSelectedItem().equals("low"))
            {
                done=false;
                secondHalfC.removeAllItems();
                secondHalfC.addItem("high");
                done=true;
            }
            else
            {
                done=false;
                secondHalfC.removeAllItems();
                secondHalfC.addItem("average");
                done=true;
            }
        }
    }//GEN-LAST:event_firstHalfCActionPerformed

    private void secondHalfCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_secondHalfCActionPerformed
        if(done)
        {
            if(secondHalfC.getSelectedItem().equals("high"))
            {
                done=false;
                firstHalfC.removeAllItems();
                firstHalfC.addItem("low");
                done=true;
            }
            else if(secondHalfC.getSelectedItem().equals("low"))
            {
                done=false;
                firstHalfC.removeAllItems();
                firstHalfC.addItem("high");
                done=true;
            }
            else
            {
                done=false;
                firstHalfC.removeAllItems();
                firstHalfC.addItem("average");
                done=true;
            }
        }
    }//GEN-LAST:event_secondHalfCActionPerformed

    private void doneBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doneBActionPerformed
     Connection con=Connect.connect();
       try
       {
           PreparedStatement pst=con.prepareStatement("update "+Basic75.loginID+"Basic set firstHalfP = ?, secondHalfP = ? where sem = ? ");
           pst.setString(1, String.valueOf(firstHalfC.getSelectedItem()));
           pst.setString(2, String.valueOf(secondHalfC.getSelectedItem()));
           pst.setInt(3,Basic75.currentSem);
           
           pst.executeUpdate();
           Basic75.firstHalfP=String.valueOf(firstHalfC.getSelectedItem());
           Basic75.secondHalfP=String.valueOf(secondHalfC.getSelectedItem());
       }
       catch(SQLException se)
       {
           System.out.println("Error in SettingsFrame.doneB(sessionPriority)"+se.getMessage());
       }
        finally
       {
           if(con!=null)
           {
               try
               {
                   con.close();
               }
               catch(SQLException se)
               {
                   System.out.println("Error in closing connection in SettingsFrame.doneB(sessionPriority)"+se.getMessage());
               }
           }
       }
    }//GEN-LAST:event_doneBActionPerformed

    private void back1LMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_back1LMouseClicked
       Basic75.hf.setHomeFrame();
        Basic75.hf.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_back1LMouseClicked

    private void back2LMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_back2LMouseClicked
        back1LMouseClicked(evt); 
    }//GEN-LAST:event_back2LMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SettingsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SettingsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SettingsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SettingsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SettingsFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel back1L;
    private javax.swing.JLabel back2L;
    private javax.swing.JButton doneB;
    private javax.swing.JComboBox<String> firstHalfC;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel messsageL;
    private javax.swing.JComboBox<String> secondHalfC;
    private javax.swing.JButton submitB;
    private javax.swing.JPanel targetP;
    // End of variables declaration//GEN-END:variables
}
